apiVersion: v1
kind: ServiceAccount
metadata:
  name: capsule-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capsule-dashboard-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "pods", "pods/log", "configmaps", "persistentvolumeclaims", "services"]
    verbs: ["get", "watch", "update", "patch", "delete", "create", "list"]
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "watch", "update", "patch", "delete", "create"]
  - apiGroups: ["capsule.clastix.io"]
    resources:
      [
        "tenants", "tenants/status", "tenants/finalizers",
      ]
    verbs: ["get", "watch", "update", "patch", "delete", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capsule-dashboard-binding
subjects:
  - kind: ServiceAccount
    name: capsule-dashboard
roleRef:
  kind: Role
  name: capsule-dashboard-role
  apiGroup: rbac.authorization.k8s.io
