apiVersion: v1
kind: ServiceAccount
metadata:
  name: capsule-dashboard
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capsule-dashboard-role
rules:
  - apiGroups: ["capsule.clastix.io"]
    resources: ["tenants", "tenants/status", "tenants/finalizers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capsule-dashboard-binding
subjects:
  - kind: ServiceAccount
    name: capsule-dashboard
    namespace: default
roleRef:
  kind: ClusterRole
  name: capsule-dashboard-role
  apiGroup: rbac.authorization.k8s.io
